// Swahili Bible book names
export const BIBLE_BOOKS = [
  // Agano la Kale (Old Testament)
  { name: "Mwanzo", testament: "AK" },
  { name: "Kutoka", testament: "AK" },
  { name: "Mambo ya Walawi", testament: "AK" },
  { name: "Hesabu", testament: "AK" },
  { name: "Kumbukumbu la Torati", testament: "AK" },
  { name: "Yoshua", testament: "AK" },
  { name: "Waamuzi", testament: "AK" },
  { name: "Ruthu", testament: "AK" },
  { name: "1 Samweli", testament: "AK" },
  { name: "2 Samweli", testament: "AK" },
  { name: "1 Wafalme", testament: "AK" },
  { name: "2 Wafalme", testament: "AK" },
  { name: "1 Mambo ya Nyakati", testament: "AK" },
  { name: "2 Mambo ya Nyakati", testament: "AK" },
  { name: "Ezra", testament: "AK" },
  { name: "Nehemia", testament: "AK" },
  { name: "Esta", testament: "AK" },
  { name: "Ayubu", testament: "AK" },
  { name: "Zaburi", testament: "AK" },
  { name: "Mithali", testament: "AK" },
  { name: "Mhubiri", testament: "AK" },
  { name: "Wimbo wa Sulemani", testament: "AK" },
  { name: "Isaya", testament: "AK" },
  { name: "Yeremia", testament: "AK" },
  { name: "Maombolezo", testament: "AK" },
  { name: "Ezekieli", testament: "AK" },
  { name: "Danieli", testament: "AK" },
  { name: "Hosea", testament: "AK" },
  { name: "Yoeli", testament: "AK" },
  { name: "Amosi", testament: "AK" },
  { name: "Obadia", testament: "AK" },
  { name: "Yona", testament: "AK" },
  { name: "Mika", testament: "AK" },
  { name: "Nahumu", testament: "AK" },
  { name: "Habakuki", testament: "AK" },
  { name: "Sefania", testament: "AK" },
  { name: "Hagai", testament: "AK" },
  { name: "Zekaria", testament: "AK" },
  { name: "Malaki", testament: "AK" },
  // Agano Jipya (New Testament)
  { name: "Mathayo", testament: "AJ" },
  { name: "Marko", testament: "AJ" },
  { name: "Luka", testament: "AJ" },
  { name: "Yohane", testament: "AJ" },
  { name: "Matendo ya Mitume", testament: "AJ" },
  { name: "Warumi", testament: "AJ" },
  { name: "1 Wakorintho", testament: "AJ" },
  { name: "2 Wakorintho", testament: "AJ" },
  { name: "Wagalatia", testament: "AJ" },
  { name: "Waefeso", testament: "AJ" },
  { name: "Wafilipi", testament: "AJ" },
  { name: "Wakolosai", testament: "AJ" },
  { name: "1 Wathesalonike", testament: "AJ" },
  { name: "2 Wathesalonike", testament: "AJ" },
  { name: "1 Timotheo", testament: "AJ" },
  { name: "2 Timotheo", testament: "AJ" },
  { name: "Tito", testament: "AJ" },
  { name: "Filemoni", testament: "AJ" },
  { name: "Waebrania", testament: "AJ" },
  { name: "Yakobo", testament: "AJ" },
  { name: "1 Petro", testament: "AJ" },
  { name: "2 Petro", testament: "AJ" },
  { name: "1 Yohane", testament: "AJ" },
  { name: "2 Yohane", testament: "AJ" },
  { name: "3 Yohane", testament: "AJ" },
  { name: "Yuda", testament: "AJ" },
  { name: "Ufunuo", testament: "AJ" },
];

export const SWAHILI_DAYS = ["Jumatatu", "Jumanne", "Jumatano", "Alhamisi", "Ijumaa", "Jumamosi", "Jumapili"];
